server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/autojobapply
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.formate_sql=true